---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: clairelovisa/test-tag-rebuilds-after-name-update
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: clairelovisa/test-tag-rebuilds-after-name-update
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: clairelovisa/test-tag-rebuilds-after-name-update
    dry_run: true
trigger:
  event:
  - pull_request

---
kind: secret
name: docker_username
data: akU/xTl6Dab/hTMo2mjWLkGv2N5F3NrYY5FaoMePcRfrp/2SxOrsbA==
---
kind: secret
name: docker_password
data: 2qMU0yF2AHLY326+2t/w+kqyrv5JIPdfiZj6F6WQjYPPgYuOMcQZn24=
---
kind: signature
hmac: nPXsCZUtXLezHknZj8shKWWjWHHaz2aEy9gtUhIOOCd0

...
